### ISSUE TITLE
FTP site

### ISSUE THREAD

**Issue by alienzj** [leylabmpi/Struo2#12]
Dear Struo2 developer,

Is the FTP site currently accessible? I want to download the built kraken2 db for GTDB R202. 

Best,
Jie

**Comment by alienzj** [comment]
You know, in the Struo2 paper: We will publish new versions of each database as new releases of the GTDB are published.

It is great ! Thanks so much ~

**Comment by alienzj** [comment]
Thanks, now I can access the FTP site.

**Comment by nick-youngblut** [comment]
>Thanks, now I can access the FTP site.
I didn't do anything. I guess that the FTP site was down for a bit of time. I'm glad you were able to access it! I am planning on creating a python script to aid in downloading all of the database files. Hopefully, I can add that soon.

**Comment by alienzj** [comment]
It is really good to use scripts to automatically download the basic files needed. Thank you ~
