### ISSUE TITLE
Cannot install the conda environment

### ISSUE THREAD

**Issue by Valentin-Bio** [leylabmpi/Struo2#13]
Hello I'm trying to install Struo2 , 

First I downloaded the repo with git clone:

`git clone https://github.com/leylabmpi/Struo2.git`

I `cd` into the downloaded Struo2/ folder 

Then when I try to install the conda environment with the suggested code:

`conda env create --name struo2 conda_env.yaml`

I got the following error message:

> SpecNotFound: Invalid name, try the format: user/package

So I tried the following:

> conda env create --name struo2 leylabmpi/Struo2.git

getting the following report:

"> >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> 
>     Traceback (most recent call last):
>       File "/data/vberrios/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1080, in __call__
>         return func(*args, **kwargs)
>       File "/data/vberrios/miniconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
>         exit_code = getattr(module, func_name)(args, parser)
>       File "/data/vberrios/miniconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 88, in execute
>         spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
>       File "/data/vberrios/miniconda3/lib/python3.8/site-packages/conda_env/specs/__init__.py", line 43, in detect
>         if spec.can_handle():
>       File "/data/vberrios/miniconda3/lib/python3.8/site-packages/conda_env/specs/binstar.py", line 38, in can_handle
>         result = self._can_handle()
>       File "/data/vberrios/miniconda3/lib/python3.8/site-packages/conda_env/specs/binstar.py", line 53, in _can_handle
>         return self.package is not None and self.valid_package()
>       File "/data/vberrios/miniconda3/lib/python3.8/site-packages/conda_env/specs/binstar.py", line 117, in package
>         self._package = self.binstar.package(self.username, self.packagename)
>       File "/data/vberrios/miniconda3/lib/python3.8/site-packages/binstar_client/__init__.py", line 299, in package
>         self._check_response(res)
>       File "/data/vberrios/miniconda3/lib/python3.8/site-packages/binstar_client/__init__.py", line 227, in _check_response
>         raise ErrCls(msg, res.status_code)
>     binstar_client.errors.BinstarError: ('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/package/leylabmpi/Struo2.git -> 403)', 403)
> 

So how can I install the program?

**Comment by nick-youngblut** [comment]
It appears that you forgot to use the `--file` parameter:

```
conda env create --name struo2 --file conda_env.yaml
```

You can speed up the process with [mamba](https://github.com/mamba-org/mamba)
