### ISSUE TITLE
creating a custom GTDB with user provided MAGs

### ISSUE THREAD

**Issue by Valentin-Bio** [leylabmpi/Struo2#14]
Hello I need to use kraken2 for mapping paired end reads a against a custom GTDB database, the issue is that I need to add some metagenome assembly genomes that I built so I think your tool may help me a lot!

The issue is that first I dont know how to do it.

I cloned the repo to my server using `git clone https://github.com/leylabmpi/Struo2.git`

Once I created the conda environment with `conda env create --name struo2 --file conda_env.yaml` im stuck with the following procedure:

> Create a directory to hold all of the necessary Struo2 data files
> The directory location can be anywhere on your file system
> OUTDIR=./data/
> mkdir -p $OUTDIR

it is supposed that I create an empty directory where I can download the following custom GTDB taxdump files ?

```
wget --directory-prefix $OUTDIR http://ftp.tue.mpg.de/ebio/projects/struo2/GTDB_release95/taxdump/names.dmp
wget --directory-prefix $OUTDIR http://ftp.tue.mpg.de/ebio/projects/struo2/GTDB_release95/taxdump/nodes.dmp
```

Or should I incorporate those taxdump files on the Struo2/data/ directory ?
  
besides that those wget command gives me the following "error 404" message

> --2021-12-07 17:37:38--  http://ftp.tue.mpg.de/ebio/projects/struo2/GTDB_release95/taxdump/names.dmp
Resolving ftp.tue.mpg.de (ftp.tue.mpg.de)... 192.124.27.90
Conecting with ftp.tue.mpg.de (ftp.tue.mpg.de)[192.124.27.90]:80... connected.
Request HTTP sent, waiting response... 404 Not Found

Is there a detailed guide on how to use this useful tool?

Thanks for your time :)

**Comment by nick-youngblut** [comment]
You can use the `./util_scripts/database_download.py` script for downloading database files
