### ISSUE TITLE
Cyclic dependency on rule copy_gene_info

### ISSUE THREAD

**Issue by yiqijiang17** [leylabmpi/Struo2#20]
Hi,
I am trying to update the HUMAnN3 with my gene sets which I noticed in another [issue](https://github.com/leylabmpi/Struo2/issues/19).
At the same time, I got an error when I try ```snakemake --use-conda -j 1 -Fqn```, I check the snakefile and think it may be a bug in this function, detailed log:

```
--Running db-update pipeline--
* Updating genes database
  * Using user-provided set of gene sequences
* Updating humann database
  * Using updated genes database
  * Annotating via "diamond blastp"
CyclicGraphException in line 191 of Struo2/bin/db_update/genes/input/from_gene_set/Snakefile:
Cyclic dependency on rule copy_gene_info.

```

Yiqi

**Comment by nick-youngblut** [comment]
@yiqijiang17 I have not been able to reproduce this error. Can you provide some more context?

**Comment by yiqijiang17** [comment]
I check again, it was my wrong manipulation. I put the output dir of genes db as the input as I didn't have the amino_acid/nucleotide/metadata of HUMANn3. Thanks for your reply
