### ISSUE TITLE
Improper visualisation of Kraken2 output after using Struo2 Kraken database files

### ISSUE THREAD

**Issue by Rohit-Satyam** [leylabmpi/Struo2#21]
Hi!!

I was trying to classify a sample using Kraken Indexes provided by you [here](http://ftp.tue.mpg.de/ebio/projects/struo2/GTDB_release202/kraken2/) since using Kraken2 PlusPF database was leading to ~74% of unclassified reads. Your database improved this classification and reduced unclassified reads to ~48%. However, when visualising Kraken2 report using Pavian R package, I am getting improper visualization as shown below:

![image](https://user-images.githubusercontent.com/55479480/171044452-c542c93c-2f0f-45c2-980f-065fe2016e18.png)

You can see the prefixes "p__, f__, s__" which usually don't come when using Kraken2 Refseq Indexes. I can remove them from the report but I am worried and wish to ask if I did something wrong?

My code is as follows:

```
kraken2 --threads 40 --paired --db /metagenomics/struo2_krakendb sample_R1_pair.fastq.gz sample_R2_pair.fastq.gz --output sample --report sample_kraken_report.txt --gzip-compressed --unclassified-out $sample_unclassified#.fastq

bracken -r 150 -d /metagenomics/struo2_krakendb -i sample_kraken_report.txt -o sample_bracken_report.txt -w sample_kraken_bracken.report

```

**Comment by Rohit-Satyam** [comment]
Thanks for the regex. I have one more query. I have first classified the reads using Kraken2 pluspf indexes and the unclassified reads were then classified using Struo2 Krakenn2 database. Now how do I combine the two Kraken2 reports. KrakenTools isn't helping and throws an error:

```r
../../../metagenomics/KrakenTools/combine_kreports.py -r sample_kraken_report.txt sample_kraken_report_sturo.txt -o combined_report.txt
>>STEP 1: READING REPORTS
        2/2 samples processedTraceback (most recent call last):
  File "../../../metagenomics/KrakenTools/combine_kreports.py", line 311, in <module>
    main()
  File "../../../metagenomics/KrakenTools/combine_kreports.py", line 226, in main
    while level_num != (prev_node.level_num + 1):
AttributeError: 'NoneType' object has no attribute 'level_num'
```

**Comment by nick-youngblut** [comment]
>Now how do I combine the two Kraken2 reports. KrakenTools isn't helping and throws an error

I wouldn't combine them, given that you would be combining 2 different taxonomies.

**Comment by Rohit-Satyam** [comment]
Okay. Then I will plot them separately!! Thanks for your prompt reply.
