### ISSUE TITLE
Troubleshooting snakemake_sge.sh

### ISSUE THREAD

**Issue by dgolden96** [leylabmpi/Struo2#22]
Hey there,

My supervisor and I have been trying to test out Kraken2 database generation, and we're running into some challenges debugging our snakemake_sge.sh call. When I run the whole script, it boots me out of my terminal session. If I just run it in chunks, I can see it starting to work, but then I get stuck in an error loop related to submitting "jobscript" and the code not being able to find a parallel environment called "parallel". Haven't been able to find anything related to those in the config files or the various scripts, so I thought I'd inquire here. I'll attach the most recent error log file as well as the config.yaml here.

Thanks in advance!
Daniel Golden
Boston University Bioinformatics
[2022-06-03T151219.260927.snakemake.log](https://github.com/leylabmpi/Struo2/files/8835203/2022-06-03T151219.260927.snakemake.log)
[config.zip](https://github.com/leylabmpi/Struo2/files/8835208/config.zip)

**Comment by nick-youngblut** [comment]
`snakemake_sge.sh` only works for an SGE HPC (submitting cluster jobs via `qsub`). Most likely, you are using an HPC with a different HPC workload manager.  See the [snakemake docs](https://snakemake.readthedocs.io/en/stable/executing/cluster.html?highlight=slurm) for more info.

**Comment by dgolden96** [comment]
Unfortunately not; I checked, and BU's shared computing cluster definitely uses SGE. I'll check the snakemake docs though! I haven't been submitting the command with a qsub script, so that could be the issue.

**Comment by dgolden96** [comment]
Not locally, no, we still ran it on BU's shared computing cluster, which does run on SGE. Once we realized that running snakemake_sge.sh as it was didn't seem to be working, we extracted the snakemake call from the script and started iterating on it a little bit. This call ended up working:

snakemake -f  --use-conda   --configfile config.yaml   --jobs 28  --printshellcmds   --resources temp=28   --directory /projectnb/microbiome/dgolden/Struo2   "${@:3}" --rerun-incomplete

Before we added the --rerun-incomplete flag, the call would start generating the database, but it would freeze up after submitting the last job.

Best,
Dan Golden
________________________________

**Comment by nick-youngblut** [comment]
Gotcha. You ran it on a node, but not across the cluster

**Comment by dgolden96** [comment]
I believe so! Sorry if I'm not being as clear as would be ideal; I'm a bit more experienced in data analysis with python and R than I am with Linux.
________________________________

**Comment by nick-youngblut** [comment]
👍 
If you ever want to run jobs across multiple nodes, you'll need to use a snakemake profile
