### ISSUE TITLE
GTDB_release207 has empty 150/200/250 Bracken files

### ISSUE THREAD

**Issue by zoey-rw** [leylabmpi/Struo2#30]
The Bracken files associated with the [newest GTDB_release207 on the FTP site ](http://ftp.tue.mpg.de/ebio/projects/struo2/GTDB_release207/kraken2/) seem to be empty for all but the 100-bp read files. When you get a chance, would you be able to generate/post those .kmer files? Or should we re-generate those files locally?

Thank you,
Zoey

**Comment by nick-youngblut** [comment]
Thanks @zoey-rw for pointing out that issue! I didn't notice that those files were empty 😱 

There is a bug in the Struo2 code that resulted in only 1 of the read length databases being generated. 
I need to re-create the other read length databases. This will likely take a day or 2

**Comment by nick-youngblut** [comment]
OK, usable versions of all of the bracken databases should now all be available at http://ftp.tue.mpg.de/ebio/projects/struo2/GTDB_release207/kraken2/

**Comment by zoey-rw** [comment]
Thank you so much for this quick update! I'm posting here because it seems related: there is also a missing seqid2taxid.map file for GTDB v207. Could the taxonomy/prelim_map.txt file be used in its place?

**Comment by nick-youngblut** [comment]
Sorry about not including the seqid2taxid.map. I've added it to the 207 release
