### ISSUE TITLE
protein kraken2 DB?

### ISSUE THREAD

**Issue by wwood** [leylabmpi/Struo2#35]
Hi,

I'm not especially familiar with the kraken and Struo2 landscape so I might have missed it, but am I right in concluding that there is no GTDB (r207) protein kraken2 DB you are aware of?

Thanks, ben

**Comment by nick-youngblut** [comment]
No, there is no proteome-based kraken2 database. The database is based on whole genome sequences

**Comment by wwood** [comment]
From the kraken2 paper there is a proteome DB, however what you are saying is that there's no GTDB version (or Bracken I think).

OK. Thanks for the quick and clear response. Feel free to close if you don't think this is an issue.
