### ISSUE TITLE
GTDB207 genes_db.tar.gz missing

### ISSUE THREAD

**Issue by SmalJonni** [leylabmpi/Struo2#36]
Hi Nick,
Thank you for your work on Struo2.

I was looking on the ftp site under /ebio/projects/struo2/GTDB_release207/genes to download the genes_db.tar.gz to update the provided humann3 GTDB207 databases with my own MAGs. However, the file does not seem to exist.

Can I substitute the file with /ebio/projects/struo2/GTDB_release202/genes/genes_db.tar.gz or is there any recommended way to avoid recomputation from scratch?

Regards

**Comment by nick-youngblut** [comment]
Thanks @SmalJonni for spotting the missing file! I've started the upload job. The file is ~45 Gb, so the upload probably won't be finished until tomorrow

**Comment by SmalJonni** [comment]
Thank you for solving the issue!
