### ISSUE TITLE
taxdump page not found

### ISSUE THREAD

**Issue by slschnorr** [leylabmpi/Struo2#4]
I'm trying to follow the instructions to download the GTDB databases for struo2 to use for kraken and bracken, and I'm quite confused by the documentation. When trying to download the taxdump files I get 404 Not Found result from the command supplied on the readme, and looking at the ftp site, indeed the specified files are not there. These instructions are for the gtdb95, is there a recommended way to set up the gtdb202?

**Comment by nick-youngblut** [comment]
Thanks for pointing out the lack of the taxdump! 
I've added the [taxdump](http://ftp.tue.mpg.de/ebio/projects/struo2/GTDB_release202/taxdump/), and I'll update the docs for using GTDBr202

**Comment by slschnorr** [comment]
Thanks a lot! Also since you are putting the names and nodes.dmp files in an archive, then one just needs to get and unpack the archive rather than the consecutive wget commands for the individual files, which is currently written into the docs. Also, the readme on https://github.com/nick-youngblut/gtdb_to_taxdump for Usage I guess has a typo since it reads Example (GTDB release95): and the files point to 202. And just to be sure, the result of using the gtdb_to_taxdump.py on the gtdb metadata would be the same as the .dmp files you are providing in the prebuilt ftp?

**Comment by nick-youngblut** [comment]
Thanks for spotting the typo for the gtdb_to_taxdump README!

**Comment by nick-youngblut** [comment]
FYI: I've added a help script for downloading the pre-built Struo2 databases: `./util_scripts/database_download.py`
