### ISSUE TITLE
Using Humann3 files for MetaPhlan?

### ISSUE THREAD

**Issue by vinisalazar** [leylabmpi/Struo2#46]
Hi,

Thank you so much for providing Struo2. I was able to succesfully create my own database for Kraken2, Humann3, and the genes database.

I was wondering if you have any experience running MetaPhlan from the files generated from Struo2. I did notice that it requires some specific data files such as `mpa_vJan21_CHOCOPhlAnSGB_202103`, but I was hoping to use only my custom database (not any of the default ones provided by the MetaPhlan developers).

Do you know if this is possible?

Thank you!!
Vini

**Comment by nick-youngblut** [comment]
> I was able to successfully create my own database for Kraken2, Humann3, and the genes database

That's great to hear!

> I was wondering if you have any experience running MetaPhlan from the files generated from Struo2

The metaphlan database is rather convoluted. Struo2 is NOT designed to generate metaphlan databases. Sorry.

**Comment by vinisalazar** [comment]
Thank you for clarifying @nick-youngblut !
